// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run over the direct (unpooled) connection on port 5432.
    // Falls back to DATABASE_URL so a local Postgres still works unchanged.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
